version: '3'
services:
  web:
    image: nginx
    volumes:
      - '/home/abelesense/projects/project1/public:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'

    ports:
      - "81:80"
  php-fpm:
    build: ./docker
    volumes:
      - '/home/abelesense/projects/project1/public:/var/www/html'

  db:
    image: postgres:14.1
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd